Add doctests for std::iter::Sum
jswrenn/nalgebra pull request #1
Opened 2019-01-01 13:32 UTC by grtlr

2019-01-01 17:49 UTC, jswrenn requested changes
Thanks! I have a few requested changes to bring the doctests in line with nalgebra's other doctests.

(The comments are on the static matrices test, but apply to the other tests, too.)

2019-01-01 17:49 UTC, jswrenn commented on src/base/ops.rs
> +/// ```.rust
You can drop the `.rust`. Unless a different language is explicitly specified, all code comments default to being interpreted as rust code.

2019-01-01 17:49 UTC, jswrenn commented on src/base/ops.rs
> +///use nalgebra::Matrix3x2;
In nalgebra's doctests, it's been customary to hide the imports from the rendered code snippets; it helps reduce visual noise when they're rendered as html. To do this, change this import to:
```
#use nalgebra::Matrix3x2;
```

2019-01-01 18:33 UTC, grtlr commented
That makes a lot of sense! I have formatted the doctests accordingly. I have also added a space behind `///` for better readability. The other tests of nalgebra seem to do it that way as well.

2019-01-02 16:07 UTC, jswrenn approved these changes

2019-01-02 16:18 UTC, merged